name: "build sample-platform"
on:
  workflow_dispatch:
    

jobs:
  call-terraform:
    uses: "padarbindaorg/platform-modules/.github/workflows/provision.yml@main"
    with:
      application_name: "sampleplatform"
      aws_region: "us-east-2"
      environment: "dev"
      backend_bucket_name: "pp-bucket"
      backend_dynamo_table_name: "my_lock_table"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_access_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      app_id: ${{ secrets.APP_ID }}
      app_secret_key: ${{ secrets.APP_SECRET_KEY }}